export const upcomingAppointments = [
  {
    id: 1,
    name: 'Dr. Kavita Rao',
    dept: 'Pediatrics',
    slot: 'Newborn Checkup',
    slottime: '30 min',
    date: 'Tue, July 9',
    time: '09:30 AM',
    location: 'Sunrise Children’s Hospital, Room 210',
    phone: '+91 9845012345',
  },
  {
    id: 2,
    name: 'Dr. Arjun Deshmukh',
    dept: 'ENT Specialist',
    slot: 'Hearing Evaluation',
    slottime: '25 min',
    date: 'Wed, July 10',
    time: '02:15 PM',
    location: 'Care ENT Center, Cabin B1',
    phone: '+91 9811056789',
  },
  {
    id: 3,
    name: 'Dr. Meera Shah',
    dept: 'Psychiatry',
    slot: 'Mental Wellness Session',
    slottime: '50 min',
    date: 'Fri, July 12',
    time: '11:00 AM',
    location: 'Tranquil Minds Clinic, Suite 5A',
    phone: '+91 9988776655',
  },
];

export const pastAppointments = [
  {
    id: 4,
    name: 'Dr. Sarah Johnson',
    dept: 'Cardiologist',
    slot: 'ECG & Consultation',
    slottime: '40 min',
    date: 'Mon, June 10',
    time: '10:00 AM',
    location: 'HeartCare Hospital, Room 304',
    phone: '+91 9797979797',
  },
  {
    id: 5,
    name: 'Dr. Rahul Mehta',
    dept: 'Orthopedic',
    slot: 'Knee Pain Follow-up',
    slottime: '35 min',
    date: 'Thu, June 13',
    time: '03:00 PM',
    location: 'City Ortho Center, Room 12B',
    phone: '+91 9876543210',
  },
  {
    id: 6,
    name: 'Dr. Priya Verma',
    dept: 'Dermatologist',
    slot: 'Acne Treatment',
    slottime: '20 min',
    date: 'Sat, June 15',
    time: '12:15 PM',
    location: 'Glow Clinic, Skin Suite 3',
    phone: '+91 9123456789',
  },
];

export const top = [
  {
    id: '1',
    type: 'color',
    backgroundColor: '#D5D1E9',
    text: 'Dr. Ayesha Rahman',
    amount: '₹14,800',
    textColor: '#fff',
    image: 'https://randomuser.me/api/portraits/women/44.jpg',
  },
  {
    id: '2',
    type: 'color',
    backgroundColor: '#D0E4EE',
    text: 'Dr. Karan Mehta',
    amount: '₹11,250',
    textColor: '#000',
    image: 'https://randomuser.me/api/portraits/men/32.jpg',
  },
  {
    id: '3',
    type: 'color',
    backgroundColor: '#F3F5A9',
    text: 'Dr. Neha Sharma',
    amount: '₹17,500',
    textColor: '#000',
    image: 'https://randomuser.me/api/portraits/women/65.jpg',
  },
];

export const bottom = [
  {
    id: '1',
    type: 'color',
    backgroundColor: '#e1f5fe',
    title: 'Dr. Ayesha Rahman',
    text: 'Consultation at 10:30 AM',
    amount: '',
    textColor: '#000',
    image: 'https://randomuser.me/api/portraits/women/44.jpg',
  },
  {
    id: '2',
    type: 'color',
    backgroundColor: '#e8f5e9',
    title: 'Dr. Karan Mehta',
    text: 'Consultation at 12:00 PM',
    amount: '',
    textColor: '#000',
    image: 'https://randomuser.me/api/portraits/men/32.jpg',
  },
  {
    id: '3',
    type: 'color',
    backgroundColor: '#fff3e0',
    title: 'Dr. Neha Sharma',
    text: 'Consultation at 03:15 PM',
    amount: '',
    textColor: '#000',
    image: 'https://randomuser.me/api/portraits/women/65.jpg',
  },
];

export const healthData = [
  {
    id: 1,
    icon: 'pulse',
    name: 'Blood Pressure',
    value: '118/76 mmHg',
    backgroundColor: '#d4fffc',
    color: 'blue',
    content: 'Normal',
  },
  {
    id: 2,
    icon: 'heart-outline',
    name: 'Heart Rate',
    value: '72 bpm',
    backgroundColor: '#f1cbff',
    color: 'red',
    content: 'Normal',
  },
  {
    id: 3,
    icon: 'person-outline',
    value: '22.4',
    backgroundColor: '#c9e7db',
    name: 'BMI',
    color: 'green',
    content: 'Healthy',
  },
];

export const Personalhealth = [
  {
    id: 1,
    icon: 'call-outline',
    name: 'Phone',
    color: '#bae1ff',
    content: '+91 9878788989',
  },
  {
    id: 2,
    icon: 'mail-outline',
    name: 'Email',
    color: '#f1cbff',
    content: 's.johnson@example.com',
  },
  {
    id: 3,
    icon: 'location-outline',
    name: 'Address',
    color: '#baffc9',
    content: '101 Rose Avenue, Bengaluru, KA 560001',
  },
  {
    id: 4,
    icon: 'heart-outline',
    name: 'Blood Group',
    color: '#ffb3ba',
    content: 'O+',
  },
];
